
function AddCloudEntity(id, x, y, z, sx, sy, sz, colorx, colory, colorz)
	Entity.New(id , 'cloud' ) 
	Entity.setActive(id , true) 
	Entity.addTag(id , "cloud") 
	Entity.getTransform.setPosition(id, x, y, z) 
	Entity.getTransform.setRotation(id, 0, 0, 0) 
	Entity.getTransform.setScale(id, sx, sy, sz) 
	Entity.addMeshRenderer(id) 
	Entity.getMeshRenderer.setName(id, 'CUBE') 
	Entity.getMeshRenderer.setColor(id, colorx, colory, colorz) 
	Entity.getMeshRenderer.setShininess(id, 32) 
	Entity.getMeshRenderer.setEmissive(id, 0) 
	Entity.addSphereCollider(id) 
	Entity.getSphereCollider.setRadius(id, 5) 
	Entity.getSphereCollider.addTag(id, "MESHCULL")
	Entity.addAABBCollider(id, 1) 
	Entity.getAABBCollider.setHalfSize(id, 1, -0.1, -0.25, -0.1)
	Entity.getAABBCollider.setPosition(id, 1, 0, 0.9, 0)
	Entity.getAABBCollider.addTag(id, 1, "cloud")
	Entity.addMeshCollider(id)
	Entity.getMeshCollider.setName(id, "CUBE")
	Entity.addScript(id) 
	Entity.getScript.setPath(id, 'Content//scripts//moveup.lua')
	Entity.addEllipsoidCollider(id)
	Entity.getEllipsoidCollider.setRadius(id, 5.5, 0.9, 5.5)
end