
function AddDinoEntity(id, x, y, z, scriptname)

  Entity.New(id , 'DinoBody' ) 
  Entity.setActive(id , true) 
  Entity.addTag(id , "enemy") 
  Entity.getTransform.setPosition(id, x, y, z) 
  Entity.getTransform.setRotation(id, 0, 0, 0) 
  Entity.getTransform.setScale(id, 2, 2, 2) 
  Entity.addMeshRenderer(id) 
  Entity.getMeshRenderer.setName(id, 'DINOBODY') 
  Entity.getMeshRenderer.setColor(id, 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id, 32) 
  Entity.getMeshRenderer.setEmissive(id, 0) 
  Entity.addSphereCollider(id) 
  Entity.getSphereCollider.setRadius(id, 25) 
  Entity.getSphereCollider.addTag(id, "MESHCULL")
  Entity.addAABBCollider(id, 1) 
  Entity.getAABBCollider.setHalfSize(id, 1, 0,0,0)
  Entity.getAABBCollider.setPosition(id, 1, 0,0,0)
  Entity.getAABBCollider.addTag(id, 1, "enemy")
  Entity.addScript(id) 
  Entity.getScript.setPath(id, 'Content//scripts//DinoBodyMovement.lua') 
  Entity.addEllipsoidCollider(id)
  Entity.getEllipsoidCollider.setRadius(id, 3, 4.75, 3)
  Entity.addDinoAI(id)

  Entity.New(id + 1 , 'DinoHead' ) 
  Entity.setActive(id + 1 , true) 
  Entity.addTag(id + 1 , "enemy")
  Entity.getTransform.setPosition(id + 1, -5, 4.8, 0) 
  Entity.getTransform.setRotation(id + 1, 0, 0, 0) 
  Entity.getTransform.setScale(id + 1, 2, 2, 2) 
  Entity.addMeshRenderer(id + 1) 
  Entity.getMeshRenderer.setName(id + 1, 'DINOHEAD') 
  Entity.getMeshRenderer.setColor(id + 1, 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id + 1, 32) 
  Entity.getMeshRenderer.setEmissive(id + 1, 0) 
  Entity.addSphereCollider(id + 1) 
  Entity.getSphereCollider.setRadius(id + 1, 5) 
  Entity.getSphereCollider.addTag(id + 1, "MESHCULL")
  Entity.addScript(id + 1) 
  Entity.getScript.setPath(id + 1, scriptname) 
  Entity.shareDinoAI(id + 1, id, 0)


  Entity.New(id + 2 , 'DinoLeftLeg' ) 
  Entity.setActive(id + 2  , true) 
  Entity.addTag(id + 2  , "enemy") 
  Entity.addParent(id + 2 ,id)
  Entity.getTransform.setPosition(id + 2 , 0, -4.8, 0) 
  Entity.getTransform.setRotation(id + 2 , 0, 0, 0) 
  Entity.getTransform.setScale(id + 2 , 2, 2, 2) 
  Entity.addMeshRenderer(id + 2 ) 
  Entity.getMeshRenderer.setName(id + 2 , 'DINOLEFTLEG') 
  Entity.getMeshRenderer.setColor(id + 2 , 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id + 2 , 32) 
  Entity.getMeshRenderer.setEmissive(id + 2 , 0) 
  Entity.addSphereCollider(id + 2 ) 
  Entity.getSphereCollider.setRadius(id + 2 , 5) 
  Entity.getSphereCollider.addTag(id + 2 , "MESHCULL")
  Entity.addScript(id + 2 ) 
  Entity.getScript.setPath(id + 2 , 'Content//scripts//DinoLeftFeetMovement.lua') 

  Entity.New(id + 3 , 'DinoRightLeg' ) 
  Entity.setActive(id + 3 , true) 
  Entity.addTag(id + 3 , "enemy") 
  Entity.addParent(id + 3,id)
  Entity.getTransform.setPosition(id + 3, 0, -4.8, 0) 
  Entity.getTransform.setRotation(id + 3, 0, 0, 0) 
  Entity.getTransform.setScale(id + 3, 2, 2, 2) 
  Entity.addMeshRenderer(id + 3) 
  Entity.getMeshRenderer.setName(id + 3, 'DINORIGHTLEG') 
  Entity.getMeshRenderer.setColor(id + 3, 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id + 3, 32) 
  Entity.getMeshRenderer.setEmissive(id + 3, 0) 
  Entity.addSphereCollider(id + 3) 
  Entity.getSphereCollider.setRadius(id + 3, 5) 
  Entity.getSphereCollider.addTag(id + 3, "MESHCULL")
  Entity.addScript(id + 3) 
  Entity.getScript.setPath(id + 3, 'Content//scripts//DinoRightFeetMovement.lua') 


  Entity.New(id + 15 , 'DinoLeftHand' ) 
  Entity.setActive(id + 15 , true) 
  Entity.addTag(id + 15 , "enemy") 
  Entity.addParent(id + 15,id)
  Entity.getTransform.setPosition(id + 15, 0, 0, 0) 
  Entity.getTransform.setRotation(id + 15, 0, 0, 0) 
  Entity.getTransform.setScale(id + 15, 2, 2, 2) 
  Entity.addMeshRenderer(id + 15) 
  Entity.getMeshRenderer.setName(id + 15, 'DINOLEFTHAND') 
  Entity.getMeshRenderer.setColor(id + 15, 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id + 15, 32) 
  Entity.getMeshRenderer.setEmissive(id + 15, 0) 
  Entity.addSphereCollider(id + 15) 
  Entity.getSphereCollider.setRadius(id + 15, 5) 
  Entity.getSphereCollider.addTag(id + 15, "MESHCULL")
  Entity.addScript(id + 15) 
  Entity.getScript.setPath(id + 15, 'Content//scripts//DinoLeftHandMovement.lua') 

  Entity.New(id + 16 , 'DinoRightHand' ) 
  Entity.setActive(id + 16 , true) 
  Entity.addTag(id + 16 , "enemy") 
  Entity.addParent(id + 16,id)
  Entity.getTransform.setPosition(id + 16, 0, 0, 0) 
  Entity.getTransform.setRotation(id + 16, 0, 0, 0) 
  Entity.getTransform.setScale(id + 16, 2, 2, 2) 
  Entity.addMeshRenderer(id + 16) 
  Entity.getMeshRenderer.setName(id + 16, 'DINORIGHTHAND') 
  Entity.getMeshRenderer.setColor(id + 16, 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id + 16, 32) 
  Entity.getMeshRenderer.setEmissive(id + 16, 0) 
  Entity.addSphereCollider(id + 16) 
  Entity.getSphereCollider.setRadius(id + 16, 5) 
  Entity.getSphereCollider.addTag(id + 16, "MESHCULL")
  Entity.addScript(id + 16) 
  Entity.getScript.setPath(id + 16, 'Content//scripts//DinoRightHandMovement.lua') 

  Entity.New(id + 4 , 'DinoTeeth' ) 
  Entity.setActive(id + 4 , true) 
  Entity.addTag(id + 4 , "enemy") 
  Entity.addParent(id + 4,id + 1)
  Entity.getTransform.setPosition(id + 4, 0, 0, 0) 
  Entity.getTransform.setRotation(id + 4, 0, 0, 0) 
  Entity.getTransform.setScale(id + 4, 2, 2, 2) 
  Entity.addMeshRenderer(id + 4) 
  Entity.getMeshRenderer.setName(id + 4, 'DINOTEETH') 
  Entity.getMeshRenderer.setColor(id + 4, 5, 5, 5) 
  Entity.getMeshRenderer.setShininess(id + 4, 32) 
  Entity.getMeshRenderer.setEmissive(id + 4, 0) 
  Entity.addSphereCollider(id + 4) 
  Entity.getSphereCollider.setRadius(id + 4, 1) 
  Entity.getSphereCollider.addTag(id + 4, "MESHCULL")

  Entity.New(id + 5 , 'DinoGlow' ) 
  Entity.setActive(id + 5 , true) 
  Entity.addTag(id + 5 , "enemy") 
  Entity.addParent(id + 5,id + 1)
  Entity.getTransform.setPosition(id + 5, 0, 0, 0) 
  Entity.getTransform.setRotation(id + 5, 0, 0, 0) 
  Entity.getTransform.setScale(id + 5, 2, 2, 2) 
  Entity.addMeshRenderer(id + 5) 
  Entity.getMeshRenderer.setName(id + 5, 'DINOGLOW') 
  Entity.getMeshRenderer.setColor(id + 5, 0.8, 0.1, 0.1) 
  Entity.getMeshRenderer.setShininess(id + 5, 32) 
  Entity.getMeshRenderer.setEmissive(id + 5, 1) 
  Entity.addSphereCollider(id + 5) 
  Entity.getSphereCollider.setRadius(id + 5, 5) 
  Entity.getSphereCollider.addTag(id + 5, "MESHCULL")

  Entity.New(id + 6 , 'DinoTailL' ) 
  Entity.setActive(id + 6 , true) 
  Entity.addTag(id + 6 , "enemy") 
  Entity.getTransform.setPosition(id + 6, 0, 0, 0) 
  Entity.getTransform.setRotation(id + 6, 0, 0, 0) 
  Entity.getTransform.setScale(id + 6, 2, 2, 2) 
  Entity.addMeshRenderer(id + 6) 
  Entity.getMeshRenderer.setName(id + 6, 'DINOTAILBIG') 
  Entity.getMeshRenderer.setColor(id + 6, 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id + 6, 32) 
  Entity.getMeshRenderer.setEmissive(id + 6, 0) 
  Entity.addSphereCollider(id + 6) 
  Entity.getSphereCollider.setRadius(id + 6, 5) 
  Entity.getSphereCollider.addTag(id + 6, "MESHCULL")
  Entity.shareDinoAI(id + 6, id, 1, 0)
  Entity.addScript(id + 6) 
  Entity.getScript.setPath(id + 6, 'Content//scripts//DinoTail.lua') 

  Entity.New(id + 7 , 'DinoTailM' ) 
  Entity.setActive(id + 7 , true) 
  Entity.addTag(id + 7 , "enemy") 
  Entity.getTransform.setPosition(id + 7, 0, -0.1, -2) 
  Entity.getTransform.setRotation(id + 7, 0, 0, 0) 
  Entity.getTransform.setScale(id + 7, 2, 2, 2) 
  Entity.addMeshRenderer(id + 7) 
  Entity.getMeshRenderer.setName(id + 7, 'DINOTAILMED') 
  Entity.getMeshRenderer.setColor(id + 7, 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id + 7, 32) 
  Entity.getMeshRenderer.setEmissive(id + 7, 0) 
  Entity.addSphereCollider(id + 7) 
  Entity.getSphereCollider.setRadius(id + 7, 5) 
  Entity.getSphereCollider.addTag(id + 7, "MESHCULL")
  Entity.shareDinoAI(id + 7, id, 1, 1)

  Entity.New(id + 8 , 'DinoTailS' ) 
  Entity.setActive(id + 8 , true) 
  Entity.addTag(id + 8 , "enemy") 
  Entity.getTransform.setPosition(id + 8, 0, -0.1, -3) 
  Entity.getTransform.setRotation(id + 8, 0, 0, 0) 
  Entity.getTransform.setScale(id + 8, 2, 2, 2) 
  Entity.addMeshRenderer(id + 8) 
  Entity.getMeshRenderer.setName(id + 8, 'DINOTAILS') 
  Entity.getMeshRenderer.setColor(id + 8, 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id + 8, 32) 
  Entity.getMeshRenderer.setEmissive(id + 8, 0) 
  Entity.addSphereCollider(id + 8) 
  Entity.getSphereCollider.setRadius(id + 8, 5) 
  Entity.getSphereCollider.addTag(id + 8, "MESHCULL")
  Entity.shareDinoAI(id + 8, id, 1, 2)

  Entity.New(id + 9 , 'DinoTailXS' ) 
  Entity.setActive(id + 9 , true) 
  Entity.addTag(id + 9 , "enemy") 
  Entity.getTransform.setPosition(id + 9, 0, -0.1, -2.8) 
  Entity.getTransform.setRotation(id + 9, 0, 0, 0) 
  Entity.getTransform.setScale(id + 9, 2, 2, 2) 
  Entity.addMeshRenderer(id + 9) 
  Entity.getMeshRenderer.setName(id + 9, 'DINOTAILXS') 
  Entity.getMeshRenderer.setColor(id + 9, 0.2, 0.9, 0.2) 
  Entity.getMeshRenderer.setShininess(id + 9, 32) 
  Entity.getMeshRenderer.setEmissive(id + 9, 0) 
  Entity.addSphereCollider(id + 9) 
  Entity.getSphereCollider.setRadius(id + 9, 5) 
  Entity.getSphereCollider.addTag(id + 9, "MESHCULL")
  Entity.shareDinoAI(id + 9, id, 1, 3)

  Entity.New(id + 10 , 'DinoTailHornL' ) 
  Entity.setActive(id + 10 , true) 
  Entity.addTag(id + 10 , "enemy") 
  Entity.addParent(id + 10,id + 6)
  Entity.getTransform.setPosition(id + 10, 0, -2.5, 3) 
  Entity.getTransform.setRotation(id + 10, 0, 0, 0) 
  Entity.getTransform.setScale(id + 10, 2, 2, 2) 
  Entity.addMeshRenderer(id + 10) 
  Entity.getMeshRenderer.setName(id + 10, 'DINOTAILHORNBIG') 
  Entity.getMeshRenderer.setColor(id + 10, 1.25, 0.5, 0.1) 
  Entity.getMeshRenderer.setShininess(id + 10, 32) 
  Entity.getMeshRenderer.setEmissive(id + 10, 0) 
  Entity.addSphereCollider(id + 10) 
  Entity.getSphereCollider.setRadius(id + 10, 5) 
  Entity.getSphereCollider.addTag(id + 10, "MESHCULL")

  Entity.New(id + 11 , 'DinoTailHornM' ) 
  Entity.setActive(id + 11 , true) 
  Entity.addTag(id + 11 , "enemy") 
  Entity.addParent(id + 11,id + 7)
  Entity.getTransform.setPosition(id + 11, 0, 0, 0) 
  Entity.getTransform.setRotation(id + 11, 0, 0, 0) 
  Entity.getTransform.setScale(id + 11, 2, 2, 2) 
  Entity.addMeshRenderer(id + 11) 
  Entity.getMeshRenderer.setName(id + 11, 'DINOTAILHORNMED') 
  Entity.getMeshRenderer.setColor(id + 11, 1.25, 0.5, 0.1) 
  Entity.getMeshRenderer.setShininess(id + 11, 32) 
  Entity.getMeshRenderer.setEmissive(id + 11, 0) 
  Entity.addSphereCollider(id + 11) 
  Entity.getSphereCollider.setRadius(id + 11, 5) 
  Entity.getSphereCollider.addTag(id + 11, "MESHCULL")

  Entity.New(id + 12 , 'DinoTailHornS' ) 
  Entity.setActive(id + 12 , true) 
  Entity.addTag(id + 12 , "enemy") 
  Entity.addParent(id + 12,id + 8)
  Entity.getTransform.setPosition(id + 12, 0, 0, 0) 
  Entity.getTransform.setRotation(id + 12, 0, 0, 0) 
  Entity.getTransform.setScale(id + 12, 2, 2, 2) 
  Entity.addMeshRenderer(id + 12) 
  Entity.getMeshRenderer.setName(id + 12, 'DINOTAILHORNS') 
  Entity.getMeshRenderer.setColor(id + 12, 1.25, 0.5, 0.1) 
  Entity.getMeshRenderer.setShininess(id + 12, 32) 
  Entity.getMeshRenderer.setEmissive(id + 12, 0) 
  Entity.addSphereCollider(id + 12) 
  Entity.getSphereCollider.setRadius(id + 12, 5) 
  Entity.getSphereCollider.addTag(id + 12, "MESHCULL")

  Entity.New(id + 13 , 'DinoTailHornXS' ) 
  Entity.setActive(id + 13 , true) 
  Entity.addTag(id + 13 , "enemy") 
  Entity.addParent(id + 13,id + 9)
  Entity.getTransform.setPosition(id + 13, 0, 0, 0) 
  Entity.getTransform.setRotation(id + 13, 0, 0, 0) 
  Entity.getTransform.setScale(id + 13, 2, 2, 2) 
  Entity.addMeshRenderer(id + 13) 
  Entity.getMeshRenderer.setName(id + 13, 'DINOTAILHORNXS') 
  Entity.getMeshRenderer.setColor(id + 13, 1.25, 0.5, 0.1) 
  Entity.getMeshRenderer.setShininess(id + 13, 32) 
  Entity.getMeshRenderer.setEmissive(id + 13, 0) 
  Entity.addSphereCollider(id + 13) 
  Entity.getSphereCollider.setRadius(id + 13, 5) 
  Entity.getSphereCollider.addTag(id + 13, "MESHCULL")

  Entity.New(id + 14 , 'DinoHorns' ) 
  Entity.setActive(id + 14 , true) 
  Entity.addTag(id + 14 , "enemy") 
  Entity.addParent(id + 14,id + 1)
  Entity.getTransform.setPosition(id + 14, 0, 0, 0) 
  Entity.getTransform.setRotation(id + 14, 0, 0, 0) 
  Entity.getTransform.setScale(id + 14, 2, 2, 2) 
  Entity.addMeshRenderer(id + 14) 
  Entity.getMeshRenderer.setName(id + 14, 'DINOHORN') 
  Entity.getMeshRenderer.setColor(id + 14, 1.25, 0.5, 0.1) 
  Entity.getMeshRenderer.setShininess(id + 14, 32) 
  Entity.getMeshRenderer.setEmissive(id + 14, 0) 
  Entity.addSphereCollider(id + 14) 
  Entity.getSphereCollider.setRadius(id + 14, 5) 
  Entity.getSphereCollider.addTag(id + 14, "MESHCULL")
  
end
