--[[ HEAD ]]--
function AddEndPointEntity(id, x, y, z, rx, ry, rz, px, py, pz)
	Entity.New(id , 'dragon head display' ) 
	Entity.setActive(id , true) 
	Entity.getTransform.setPosition(id, x, y, z) 
	Entity.getTransform.setRotation(id, rx, ry, rz) 
	Entity.getTransform.setScale(id, 20.5, 20.5, 22.0) 
	Entity.addMeshRenderer(id) 
	Entity.getMeshRenderer.setName(id, 'DRAGONHEAD') 
	Entity.getMeshRenderer.setColor(id, 4.0, 4.0, 4.0) 
	Entity.getMeshRenderer.setShininess(id, 64) 
	Entity.getMeshRenderer.setEmissive(id, 0) 
	Entity.addSphereCollider(id) 
	Entity.getSphereCollider.setRadius(id, 25) 
	Entity.getSphereCollider.addTag(id, "MESHCULL")
	Entity.addMeshCollider(id)
	Entity.getMeshCollider.setName(id, "DRAGONHEADC")
	Entity.addAABBCollider(id, 1) 
	Entity.getAABBCollider.setHalfSize(id, 1, 3,3,3)
	Entity.getAABBCollider.setPosition(id, 1, 0,0,0)
	Entity.getAABBCollider.addTag(id, 1, "end point")
	Entity.addScript(id) 
	Entity.getScript.setPath(id, 'Content//scripts//endgame.lua')

	Entity.New(id + 1 , 'dragon horn display' ) 
	Entity.setActive(id + 1 , true) 
	Entity.addParent(id + 1, 400)
	Entity.getTransform.setPosition(id + 1, 0, 0, 0) 
	Entity.getTransform.setRotation(id + 1, 0, 0, 0) 
	Entity.getTransform.setScale(id + 1, 20.5, 20.5, 22.0) 
	Entity.addMeshRenderer(id + 1) 
	Entity.getMeshRenderer.setName(id + 1, 'DRAGONHEADHORN') 
	Entity.getMeshRenderer.setColor(id + 1, 5.0, 5.0, 5.0) 
	Entity.getMeshRenderer.setShininess(id + 1, 64) 
	Entity.getMeshRenderer.setEmissive(id + 1, 0)
	Entity.addSphereCollider(id + 1) 
	Entity.getSphereCollider.setRadius(id + 1, 25) 
	Entity.getSphereCollider.addTag(id + 1, "MESHCULL")

	Entity.New(id + 2 , 'dragon teeth display' ) 
	Entity.setActive(id + 2 , true) 
	Entity.addParent(id + 2, 400)
	Entity.getTransform.setPosition(id + 2, 0, 0, 0) 
	Entity.getTransform.setRotation(id + 2, 0, 0, 0) 
	Entity.getTransform.setScale(id + 2, 20.5, 20.5, 22.0) 
	Entity.addMeshRenderer(id + 2) 
	Entity.getMeshRenderer.setName(id + 2, 'DRAGONTEETHUP') 
	Entity.getMeshRenderer.setColor(id + 2, 5.0, 5.0, 5.0) 
	Entity.getMeshRenderer.setShininess(id + 2, 64) 
	Entity.getMeshRenderer.setEmissive(id + 2, 0)
	Entity.addSphereCollider(id + 2) 
	Entity.getSphereCollider.setRadius(id + 2, 25) 
	Entity.getSphereCollider.addTag(id + 2, "MESHCULL")
	Entity.addMeshCollider(id + 2)
	Entity.getMeshCollider.setName(id + 2, "DRAGONTEETHUPC")
	Entity.addTrigger(id + 2)
	Entity.addScript(id + 2) 
	Entity.getScript.setPath(id + 2, 'Content//scripts//TeethMoveUp.lua')
	

	Entity.New(id + 3 , 'dragon teeth display' ) 
	Entity.setActive(id + 3 , true) 
	Entity.addParent(id + 3, 400)
	Entity.getTransform.setPosition(id + 3, 0, 0.5, 0) 
	Entity.getTransform.setRotation(id + 3, 0, 0, 0) 
	Entity.getTransform.setScale(id + 3, 20.5, 20.5, 22.0) 
	Entity.addMeshRenderer(id + 3) 
	Entity.getMeshRenderer.setName(id + 3, 'DRAGONTEETHDOWN') 
	Entity.getMeshRenderer.setColor(id + 3, 5.0, 5.0, 5.0) 
	Entity.getMeshRenderer.setShininess(id + 3, 64) 
	Entity.getMeshRenderer.setEmissive(id + 3, 0)
	Entity.addSphereCollider(id + 3) 
	Entity.getSphereCollider.setRadius(id + 3, 25) 
	Entity.getSphereCollider.addTag(id + 3, "MESHCULL")
	Entity.addMeshCollider(id + 3)
	Entity.getMeshCollider.setName(id + 3, "DRAGONTEETHDOWNC")
	Entity.TriggerLock(id + 3, id + 2)
	Entity.addScript(id + 3) 
	Entity.getScript.setPath(id + 3, 'Content//scripts//TeethMoveDown.lua')

	Entity.New(id + 4 , 'dragon cube display' ) 
	Entity.setActive(id + 4 , true) 
	Entity.addParent(id + 4, 400)
	Entity.getTransform.setPosition(id + 4, 0, 0, 0) 
	Entity.getTransform.setRotation(id + 4, 0, 0, 0) 
	Entity.getTransform.setScale(id + 4, 20.5, 20.5, 22.0) 
	Entity.addMeshRenderer(id + 4) 
	Entity.getMeshRenderer.setName(id + 4, 'DRAGONPOWERCUBE') 
	Entity.getMeshRenderer.setColor(id + 4, 0.25, 1.0, 0.3) 
	Entity.getMeshRenderer.setShininess(id + 4, 64) 
	Entity.getMeshRenderer.setEmissive(id + 4, 1)
	Entity.addSphereCollider(id + 4) 
	Entity.getSphereCollider.setRadius(id + 4, 25) 
	Entity.getSphereCollider.addTag(id + 4, "MESHCULL")
	
	
	Entity.New(id + 5 , 'button' ) 
	Entity.setActive(id + 5 , true) 
	Entity.addTag(id + 5 , "button") 
	Entity.getTransform.setPosition(id + 5, px, py, pz) 
	Entity.getTransform.setRotation(id + 5, 0, 0, 0) 
	Entity.getTransform.setScale(id + 5, 4, 2, 4) 
	Entity.addMeshRenderer(id + 5) 
	Entity.getMeshRenderer.setName(id + 5, 'LEVELROUND') 
	Entity.getMeshRenderer.setColor(id + 5, 1, 0.5, 0.1) 
	Entity.getMeshRenderer.setShininess(id + 5, 32) 
	Entity.getMeshRenderer.setEmissive(id + 5, 0) 
	Entity.addSphereCollider(id + 5) 
	Entity.getSphereCollider.setRadius(id + 5, 5) 
	Entity.getSphereCollider.addTag(id + 5, "MESHCULL")
	Entity.addAABBCollider(id + 5, 1) 
	Entity.getAABBCollider.setHalfSize(id + 5, 1, -0.1, -0.25, -0.1)
	Entity.getAABBCollider.setPosition(id + 5, 1, 0, 0.9, 0)
	Entity.getAABBCollider.addTag(id + 5, 1, "button")
	Entity.addMeshCollider(id + 5)
	Entity.getMeshCollider.setName(id + 5, "LEVELROUNDC")
	Entity.addScript(id + 5) 
	Entity.getScript.setPath(id + 5, 'Content//scripts//HeadButton.lua')
	Entity.TriggerLock(id + 5, id + 2)
	
	
end