
function AddPlatformEntity(id, x, y, z, sx, sy, sz, rx, ry, rz)
	Entity.New(id , 'big platform' ) 
	Entity.setActive(id , true) 
	Entity.addTag(id , "wall") 
	Entity.getTransform.setPosition(id, x, y, z) 
	Entity.getTransform.setRotation(id, rx, ry, rz) 
	Entity.getTransform.setScale(id, sx, sy, sz) 
	Entity.addMeshRenderer(id) 
	Entity.getMeshRenderer.setName(id, 'CUBE') 
	Entity.getMeshRenderer.setColor(id, 0.8, 0.8, 0.8) 
	Entity.getMeshRenderer.setShininess(id, 32) 
	Entity.getMeshRenderer.setEmissive(id, 0) 
	Entity.addSphereCollider(id) 
	Entity.getSphereCollider.setRadius(id, 50) 
	Entity.getSphereCollider.addTag(id, "MESHCULL")
	Entity.addAABBCollider(id, 1) 
	Entity.getAABBCollider.setHalfSize(id, 1, 0, 0, 0)
	Entity.getAABBCollider.setPosition(id, 1, 0, 0, 0)
	Entity.getAABBCollider.addTag(id, 1, "wall")
	Entity.addMeshCollider(id)
	Entity.getMeshCollider.setName(id, "CUBE")
end